apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-resources.fullname" . }}-secret
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-password: {{ .Values.secret.dbPassword | b64enc | quote }}
  db-username: {{ .Values.secret.dbUsername | b64enc | quote }}
  redis-password: {{ .Values.secret.redisPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secret.jwtSecret | b64enc | quote }}